# ========================================
# 2D-to-3D Pipeline Configuration
# ========================================

# ----------------------------------------
# Environment Configuration
# ----------------------------------------
conda_exe: "conda"
imagen_env: "imagen"              # For Imagen 3 generation
marigold_env: "marigold"          # For depth estimation
depth_env: "depth-to-3d"          # For 3D extrusion
photo_prep_env: "photo-prep"      # For photo enhancement (if needed)
use_conda: true

# ----------------------------------------
# File Paths (relative to pipeline folder)
# ----------------------------------------
marigold_cli: "../scripts/depth_generation/marigold_cli.py"
extrude_cli: "../scripts/model_generation/extrude_cli.py"
rembg_models: "../models/rembg_models"

# Folder Structure
dir_ai_generated: "../data/AI_files"      # AI-generated images
dir_photos: "../data/Photos"              # User photos (may need enhancement)
dir_3d: "../data/3D_files"                # All 3D outputs
dir_enhanced: "../data/Photos_enhanced"   # Enhanced photos cache

# ----------------------------------------
# AI Image Generation
# ----------------------------------------
prompts_file: "prompts.json"           # Path to prompt templates (relative to pipeline/)
default_prompt_view: "side_profile"    # Default view type
default_prompt_style: "standard"       # Default style

# ----------------------------------------
# Photo Enhancement (Auto-Applied)
# ----------------------------------------
auto_enhance_photos: true                 # Auto-enhance photos from photos/ folder
auto_enhance_preset: "minimal"            # Options: "none", "minimal", "balanced", "heavy"
# Note: AI images skip enhancement (already optimized)

# ----------------------------------------
# Background Removal
# ----------------------------------------
remove_background: true
bg_removal_method: "rembg"  # "removebg" ($0.20/image) or "rembg" (free)
bg_removal_model: "isnet-general-use"
bg_crop_enabled: true
bg_crop_margin: 10
mask_depth_map: true

# ----------------------------------------
# 3D Generation Method
# ----------------------------------------
# Primary method for depth generation
depth_method: "marigold"                  # Options: "marigold", "triposr" (not yet implemented)

# TripoSR settings (placeholder for future)
enable_triposr: false                     # Set to true when ready to use
triposr_settings:
  marching_cubes_resolution: 256
  target_faces: 50000
  device: "cuda"

# ----------------------------------------
# Marigold Depth Generation Presets
# ----------------------------------------
marigold_presets:
  
  low_quality:
    marigold_steps: 5
    marigold_ensemble: 1
    marigold_processing_res: 512
    marigold_match_input_res: false
    marigold_enhance_photo: true
  
  medium_quality:
    marigold_steps: 10
    marigold_ensemble: 3
    marigold_processing_res: 768
    marigold_match_input_res: false
    marigold_enhance_photo: true

  high_quality:
    marigold_steps: 20
    marigold_ensemble: 5
    marigold_processing_res: 1024
    marigold_match_input_res: false
    marigold_enhance_photo: false

# ----------------------------------------
# 3D Extrusion Parameters
# ----------------------------------------
extrude_defaults:
  width_mm: 100.0
  max_height_mm: null
  smoothing: 3
  near_offset: 0.0
  far_offset: 1
  emboss: 0.2
  f_thic: 0.00
  f_near: -0.0
  f_back: 0.00
  vertex_colors: false
  scene_lights: false
  prepare_for_3d_printing: true
  zip_outputs: false

# ----------------------------------------
# Region-Specific Processing
# ----------------------------------------
region_processing:
  enabled: false
  use_sam: true
  blend_width: 30
  detection_mode: 'prompt'                # 'human', 'contour', prompt', 'automatic'
  detection_prompt: "cow face. cow head. goat face. animal face. animal head. animal body"
  prompt_confidence: 0.25
  min_subject_size_percent: 5.0
  
  face:
    preprocessing:
      denoise_strength: 8
      clahe_clip: 3.0
      sharpen_radius: 2
      sharpen_percent: 200
      sharpen_threshold: 2
      enhance_details: 1.5
      bilateral_filter: false
    marigold:
      steps: 30
      ensemble: 10
      processing_res: 1024
      match_input_res: false

  background:
    preprocessing:
      denoise_strength: 15
      clahe_clip: 1.5
      sharpen_radius: 2
      sharpen_percent: 100
      sharpen_threshold: 3
      enhance_details: 0
      bilateral_filter: true
      bilateral_d: 9
      bilateral_sigma: 75
    marigold:
      steps: 15
      ensemble: 5
      processing_res: 768
      match_input_res: false

# ----------------------------------------
# Advanced Post-Processing (NEW)
# ----------------------------------------
enable_advanced_postprocessing: false      # Apply MakerWorld-style mesh optimization
postprocessing_settings:
  relief_height_mm: 10.0                  # Target relief height
  base_thickness_mm: 2.0                  # Base plate thickness
  target_faces: 50000                     # Face count after decimation
  smoothing_iterations: 2                 # Surface smoothing passes
  repair_mesh: true                       # Fix non-manifold edges, holes, etc.
  save_intermediate: true                 # Keep both raw and optimized STLs

# ----------------------------------------
# Output File Formats
# ----------------------------------------
export_formats:
  stl: true                               # Always needed for CNC
  glb: false                              # Set true if you want GLB files
  obj: false                              # Set true if you want OBJ files
delete_source_after_processing: true      # Deletes original file
