# ========================================
# 2D-to-3D Pipeline Configuration
# ========================================

# ----------------------------------------
# Environment Configuration
# ----------------------------------------
conda_exe: "conda"
imagen_env: "imagen"              # For Imagen 3 generation
marigold_env: "marigold"          # For depth estimation
depth_env: "depth-to-3d"          # For 3D extrusion
photo_prep_env: "photo-prep"      # For photo enhancement (if needed)
use_conda: true

# ----------------------------------------
# File Paths (relative to pipeline folder)
# ----------------------------------------
marigold_cli: "../scripts/depth_generation/marigold_cli.py"
extrude_cli: "../scripts/model_generation/extrude_cli.py"
rembg_models: "../models/rembg_models"

# Folder Structure
dir_ai_generated: "../data/AI_files"      # AI-generated images
dir_photos: "../data/Photos"              # User photos (may need enhancement)
dir_3d: "../data/3D_files"                # All 3D outputs
dir_enhanced: "../data/Photos_enhanced"   # Enhanced photos cache

# ----------------------------------------
# AI Image Generation Prompts
# ----------------------------------------
prompts_file: "prompts.json"           # Path to prompt templates (relative to pipeline/)
default_prompt_view: "side_profile"    # Default view type
default_prompt_style: "standard"       # Default style
allow_custom_prompts: true       # Allow users to enter full custom prompts

# ----------------------------------------
# Photo Enhancement (Auto-Applied)
# ----------------------------------------
auto_enhance_photos: false                 # Auto-enhance photos from photos/ folder
auto_enhance_preset: "minimal"            # Options: "none", "minimal", "balanced", "heavy"

# ----------------------------------------
# Background Removal
# ----------------------------------------
remove_background: true
bg_removal_method: "rembg"  # "removebg" ($0.01/image) or "rembg" (free)
bg_removal_model: "isnet-general-use"
bg_crop_enabled: true
bg_crop_margin: 10
mask_depth_map: true

# ----------------------------------------
# 3D Generation Method
# ----------------------------------------
# Primary method for depth generation
depth_method: "marigold"                  # Options: "marigold", "triposr" (not yet implemented)

# TripoSR settings (placeholder for future)
enable_triposr: false                     # Set to true when ready to use
triposr_settings:
  marching_cubes_resolution: 256
  target_faces: 50000
  device: "cuda"

# ----------------------------------------
# Segment Processing (for cropped regions)
# ----------------------------------------
segment_processing:
  enabled: false                    # Enable for manual segment workflow
  upscale_before_depth: true        # AI upscale segments
  upscale_factor: 4                 # 2x or 4x
  upscale_method: "auto"            # "auto", "realesrgan", "pillow"
  use_native_resolution: true       # Don't downscale in Marigold
  add_context_padding: true         # Add blurred background for context
  padding_percent: 10               # % of image to add as padding

# ----------------------------------------
# Marigold Depth Generation Presets
# ----------------------------------------
marigold_presets:
  
  low_quality:
    marigold_steps: 5
    marigold_ensemble: 1
    marigold_processing_res: 512
    marigold_match_input_res: false
    marigold_enhance_photo: true
  
  medium_quality:
    marigold_steps: 10
    marigold_ensemble: 3
    marigold_processing_res: 768
    marigold_match_input_res: false
    marigold_enhance_photo: true

  high_quality:
    marigold_steps: 20
    marigold_ensemble: 5
    marigold_processing_res: 1024
    marigold_match_input_res: false
    marigold_enhance_photo: false

# ----------------------------------------
# Marigold Depth Generation
# ----------------------------------------
marigold_background_color: "gray"  # Options: "gray", "white", "black", "light_gray", "dark_gray", or hex "#RRGGBB"
# Gray (128,128,128) = neutral mid-depth
# White (255,255,255) = far depth (background recedes)
# Black (0,0,0) = near depth (background comes forward)

# ----------------------------------------
# 3D Extrusion Parameters
# ----------------------------------------
extrude_defaults:
  width_mm: 100.0
  max_height_mm: null
  smoothing: 3
  near_offset: 0.0
  far_offset: 1
  emboss: 0.2
  f_thic: 0.0
  f_near: -0.0
  f_back: 0.05
  vertex_colors: false
  scene_lights: false
  prepare_for_3d_printing: true
  zip_outputs: false
  # Output formats (at least one must be true)
  output_stl: true          # STL format (3D printing standard)
  output_glb: false         # GLB format (web viewing, has colors/lights)
  output_obj: false         # OBJ format (widely supported)

# ----------------------------------------
# Region-Specific Processing
# ----------------------------------------
region_processing:
  enabled: false
  use_sam: true
  blend_width: 30
  detection_mode: 'prompt'                # 'human', 'contour', prompt', 'automatic'
  detection_prompt: "cow face. cow head. goat face. animal face. animal head. animal body"
  prompt_confidence: 0.25
  min_subject_size_percent: 5.0
  
  face:
    preprocessing:
      denoise_strength: 8
      clahe_clip: 3.0
      sharpen_radius: 2
      sharpen_percent: 200
      sharpen_threshold: 2
      enhance_details: 1.5
      bilateral_filter: false
    marigold:
      steps: 30
      ensemble: 10
      processing_res: 1024
      match_input_res: false

  background:
    preprocessing:
      denoise_strength: 15
      clahe_clip: 1.5
      sharpen_radius: 2
      sharpen_percent: 100
      sharpen_threshold: 3
      enhance_details: 0
      bilateral_filter: true
      bilateral_d: 9
      bilateral_sigma: 75
    marigold:
      steps: 15
      ensemble: 5
      processing_res: 768
      match_input_res: false

# ----------------------------------------
# Mesh Repair & Optimization
# ----------------------------------------
enable_mesh_repair: "auto"
trim_borders_before_repair: false
mesh_repair_settings:
  smooth_iterations: 1           # Keep minimal
  target_faces: 0                # No decimation by default
  fill_holes: false              # CHANGED: Don't fill holes in relief models
  ensure_manifold: false         # CHANGED: Relief models aren't manifold volumes
  save_before_repair: true

# Quality-dependent repair rules
mesh_repair_by_quality:
  low_quality:
    enabled: false
  medium_quality:
    enabled: false
    smooth_iterations: 1         # REDUCED from 2
    target_faces: 100000
    fill_holes: false            # ADDED
    ensure_manifold: false       # ADDED
  high_quality:
    enabled: true
    smooth_iterations: 1         # REDUCED from 2
    target_faces: 200000
    fill_holes: false            # ADDED
    ensure_manifold: false       # ADDED

# ----------------------------------------
# AI Enhancement (before depth generation)
# ----------------------------------------
ai_enhancement:
  enabled: true  # Set to false to skip AI enhancement
  
  # Upscaling method
  upscale_method: "realesrgan"  # Great general purpose
  #upscale_method: "lanczos"  # Fast!
  #upscale_method: "waifu2x"  # Great for anime characters
  #upscale_method: "gfpgan"  # Specialized for faces
  
  upscale_factor: 4  # Options: 2, 4, or 8 (higher = slower, more detail)
  max_input_size: 2048  # Max dimension before auto-switching to LANCZOS (prevents OOM)
  
  # Enhancement parameters
  clarity_strength: 1.3  # 0.5-2.0 (edge-preserving smoothing)
  detail_amount: 1.2     # 0.5-3.0 (fine detail enhancement)
  sharpen_strength: 150  # 50-300 (final sharpening pass)
  
  # Auto-install missing dependencies
  auto_install_dependencies: true  # If false, fail instead of auto-installing


delete_source_after_processing: false      # Deletes original file
